import type { Preset } from '@/types';

/**
 * The shipped presets. They intentionally use only the Basic group so they
 * visibly change the image with the current shader pipeline. Values are chosen
 * to be tasteful starting points, not destructive looks.
 */

const AT = 0; // stable timestamp for built-ins (not user-created)

function preset(
  id: string,
  name: string,
  category: Preset['category'],
  basic: NonNullable<Preset['adjustments']['basic']>,
  colorGrading?: Preset['adjustments']['colorGrading'],
): Preset {
  return {
    id,
    name,
    category,
    favorite: false,
    builtin: true,
    createdAt: AT,
    updatedAt: AT,
    adjustments: { basic, ...(colorGrading ? { colorGrading } : {}) },
  };
}

export const BUILTIN_PRESETS: readonly Preset[] = [
  preset('builtin-portrait', 'Portrait', 'portrait', {
    exposure: 0.1,
    contrast: -10,
    highlights: -15,
    shadows: 20,
    whites: 5,
    blacks: 5,
    temperature: 8,
    tint: 3,
    vibrance: 12,
    saturation: -3,
  }),
  preset('builtin-landscape', 'Landscape', 'landscape', {
    contrast: 18,
    highlights: -20,
    shadows: 15,
    whites: 10,
    blacks: -8,
    temperature: -3,
    vibrance: 25,
    saturation: 5,
  }),
  preset('builtin-night', 'Night', 'night', {
    exposure: 0.3,
    contrast: 8,
    highlights: -25,
    shadows: 30,
    blacks: -10,
    temperature: -12,
    vibrance: 10,
  }),
  preset('builtin-vintage', 'Vintage', 'vintage', {
    contrast: -18,
    highlights: -10,
    blacks: 18,
    temperature: 10,
    tint: 6,
    saturation: -18,
    vibrance: 5,
  }),
  preset('builtin-film', 'Film', 'film', {
    contrast: 6,
    highlights: -12,
    blacks: 10,
    temperature: 4,
    saturation: -8,
    vibrance: 14,
  }),
  preset('builtin-cinematic', 'Cinematic', 'cinematic', {
    contrast: 14,
    highlights: -18,
    shadows: 12,
    blacks: 6,
    temperature: 6,
    tint: -4,
    saturation: -6,
    vibrance: 8,
  }),
  preset('builtin-street', 'Street', 'street', {
    contrast: 22,
    highlights: -10,
    shadows: -5,
    blacks: -12,
    saturation: -10,
    vibrance: 6,
  }),
  preset('builtin-wedding', 'Wedding', 'wedding', {
    exposure: 0.25,
    contrast: -12,
    highlights: -10,
    shadows: 18,
    whites: 12,
    blacks: 8,
    temperature: 5,
    vibrance: 8,
    saturation: -4,
  }),
  preset('builtin-travel', 'Travel', 'travel', {
    contrast: 12,
    highlights: -12,
    shadows: 12,
    whites: 6,
    temperature: 2,
    vibrance: 22,
    saturation: 8,
  }),
  preset('builtin-bw', 'Black & White', 'bw', {
    contrast: 14,
    highlights: -8,
    shadows: 6,
    whites: 6,
    blacks: -6,
    saturation: -100,
  }),
  preset('builtin-night-sports', 'Night Sports', 'night', {
    exposure: 0.6,
    contrast: 20,
    highlights: -15,
    shadows: 25,
    whites: 8,
    blacks: -15,
    temperature: -6,
    vibrance: 15,
    saturation: 3,
  }),
  preset('builtin-highkey', 'High Key', 'portrait', {
    exposure: 0.5,
    contrast: -10,
    highlights: -5,
    shadows: 30,
    whites: 20,
    blacks: 15,
    vibrance: 5,
    saturation: -5,
  }),
  preset('builtin-moody', 'Moody', 'cinematic', {
    exposure: -0.15,
    contrast: 20,
    highlights: -20,
    shadows: -10,
    blacks: 10,
    temperature: -4,
    tint: 2,
    saturation: -12,
    vibrance: 6,
  }),
  preset('builtin-golden-hour', 'Golden Hour', 'landscape', {
    exposure: 0.15,
    contrast: 8,
    highlights: -12,
    shadows: 18,
    whites: 8,
    temperature: 22,
    tint: 6,
    vibrance: 18,
    saturation: 4,
  }),
  preset('builtin-teal-orange', 'Teal & Orange', 'cinematic', {
    contrast: 16,
    highlights: -14,
    shadows: 8,
    blacks: 6,
    temperature: 10,
    tint: -6,
    vibrance: 20,
    saturation: -2,
  }),
  preset('builtin-airy', 'Bright & Airy', 'wedding', {
    exposure: 0.35,
    contrast: -14,
    highlights: -10,
    shadows: 26,
    whites: 12,
    blacks: 12,
    temperature: 4,
    tint: 2,
    vibrance: 8,
    saturation: -4,
  }),
  preset('builtin-matte-fade', 'Matte Fade', 'film', {
    contrast: -18,
    highlights: -8,
    shadows: 14,
    blacks: 20,
    whites: -6,
    temperature: 3,
    saturation: -10,
    vibrance: 6,
  }),
  preset('builtin-cool-blue', 'Cool Blue', 'landscape', {
    contrast: 12,
    highlights: -10,
    shadows: 10,
    temperature: -20,
    tint: -4,
    vibrance: 16,
    saturation: 2,
  }),
  preset('builtin-warm-sunset', 'Warm Sunset', 'travel', {
    exposure: 0.1,
    contrast: 10,
    highlights: -18,
    shadows: 16,
    temperature: 28,
    tint: 8,
    vibrance: 20,
    saturation: 6,
  }),
  preset('builtin-vivid-pop', 'Vivid Pop', 'travel', {
    contrast: 22,
    highlights: -12,
    shadows: 12,
    whites: 10,
    blacks: -6,
    vibrance: 35,
    saturation: 12,
  }),
  preset('builtin-soft-pastel', 'Soft Pastel', 'portrait', {
    exposure: 0.2,
    contrast: -16,
    highlights: -12,
    shadows: 20,
    whites: 6,
    temperature: 6,
    tint: 4,
    saturation: -14,
    vibrance: 6,
  }),
  preset('builtin-autumn', 'Autumn', 'landscape', {
    contrast: 12,
    highlights: -14,
    shadows: 12,
    temperature: 16,
    tint: 6,
    vibrance: 22,
    saturation: 4,
  }),
  preset('builtin-winter', 'Winter', 'landscape', {
    exposure: 0.1,
    contrast: 14,
    highlights: -8,
    shadows: 10,
    temperature: -16,
    tint: -2,
    vibrance: 10,
    saturation: -4,
  }),
  preset('builtin-dramatic-bw', 'Dramatic B&W', 'bw', {
    contrast: 30,
    highlights: -24,
    shadows: -8,
    whites: 12,
    blacks: 14,
    saturation: -100,
  }),
  preset('builtin-clean', 'Clean', 'portrait', {
    contrast: 6,
    highlights: -8,
    shadows: 10,
    whites: 6,
    blacks: 4,
    vibrance: 8,
  }),
  preset('builtin-noir', 'Noir', 'bw', {
    exposure: -0.1,
    contrast: 34,
    highlights: -18,
    shadows: -14,
    blacks: 18,
    saturation: -100,
  }),

  // Split-tone / color-grading looks (use the color grading wheels).
  preset(
    'builtin-cine-tealorange',
    'Cine Teal/Orange',
    'cinematic',
    { contrast: 12, highlights: -10, shadows: 8, vibrance: 10 },
    {
      shadows: { hue: 200, saturation: 30, luminance: 0 },
      midtones: { hue: 0, saturation: 0, luminance: 0 },
      highlights: { hue: 32, saturation: 28, luminance: 0 },
      global: { hue: 0, saturation: 0, luminance: 0 },
      blending: 55,
      balance: 0,
    },
  ),
  preset(
    'builtin-warm-shadows',
    'Warm Shadows',
    'portrait',
    { exposure: 0.1, contrast: 6, shadows: 12 },
    {
      shadows: { hue: 34, saturation: 22, luminance: 0 },
      midtones: { hue: 0, saturation: 0, luminance: 0 },
      highlights: { hue: 48, saturation: 10, luminance: 0 },
      global: { hue: 0, saturation: 0, luminance: 0 },
      blending: 50,
      balance: 10,
    },
  ),
  preset(
    'builtin-cold-film',
    'Cold Film',
    'film',
    { contrast: 8, highlights: -6, blacks: 10, vibrance: -6 },
    {
      shadows: { hue: 220, saturation: 26, luminance: 0 },
      midtones: { hue: 210, saturation: 8, luminance: 0 },
      highlights: { hue: 190, saturation: 14, luminance: 0 },
      global: { hue: 0, saturation: 0, luminance: 0 },
      blending: 60,
      balance: -10,
    },
  ),
  preset(
    'builtin-vintage-fade',
    'Vintage Fade',
    'vintage',
    { contrast: -8, highlights: -12, blacks: 22, saturation: -10 },
    {
      shadows: { hue: 60, saturation: 18, luminance: 6 },
      midtones: { hue: 0, saturation: 0, luminance: 0 },
      highlights: { hue: 40, saturation: 20, luminance: 0 },
      global: { hue: 30, saturation: 8, luminance: 0 },
      blending: 50,
      balance: 0,
    },
  ),
];
