import { chapter, doc } from '../build';
import type { Track } from '../types';

const K = (path: string) => `https://kubernetes.io/docs/${path}`;

export const k8sTrack: Track = {
  id: 'k8s',
  title: 'Kubernetes',
  goal: 'CKA / CKAD 相当の操作力と、本番で「なぜ壊れたか」を切り分ける判断力',
  phase: 'P3',
  chapters: [
    chapter('k8s', 1, 'クラスタの解剖', 'なぜオーケストレータが要るのか、そして誰が何を担当しているのか。',
      [doc('Cluster Architecture', K('concepts/architecture/'))], [
        ['why-orchestration', 'コンテナだけでは足りない理由', 'concept', 8],
        ['control-plane', 'apiserver / etcd / scheduler / controller-manager の役割分担', 'concept', 12,
          [doc('Control Plane Components', K('concepts/overview/components/'))]],
        ['node-components', 'kubelet と kube-proxy、CRI / CNI / CSI の境界', 'concept', 10,
          [doc('Node Components', K('concepts/overview/components/'))]],
        ['first-kubectl', 'kubectl get / describe でクラスタを歩く', 'drill', 10,
          [doc('kubectl overview', K('reference/kubectl/'))]],
      ]),
    chapter('k8s', 2, 'Pod の解剖', '最小単位の中身。共有される名前空間と、複数コンテナの設計。',
      [doc('Pods', K('concepts/workloads/pods/'))], [
        ['pod-anatomy', 'Pod が共有するもの（ネットワーク名前空間と pause）', 'concept', 10],
        ['multi-container', 'sidecar / ambassador / adapter の使い分け', 'concept', 12],
        ['init-containers', 'initContainer で起動順を保証する', 'drill', 10,
          [doc('Init Containers', K('concepts/workloads/pods/init-containers/'))]],
        ['pod-lifecycle', 'Pending → Running → Succeeded/Failed の遷移を読む', 'drill', 12,
          [doc('Pod Lifecycle', K('concepts/workloads/pods/pod-lifecycle/'))]],
        ['boss-stuck-pending', 'BOSS: Pod が Pending から動かない', 'boss', 20,
          [doc('Debug Pods', K('tasks/debug/debug-application/debug-pods/'))]],
      ]),
    chapter('k8s', 3, '宣言的管理', '「こうあってほしい」を書いて、あとは収束させる。',
      [doc('Object Management', K('concepts/overview/working-with-objects/object-management/'))], [
        ['apply-vs-create', 'apply と create の違い、そして 3-way merge patch', 'concept', 12],
        ['labels-selectors', 'ラベルとセレクタで対象を集合として扱う', 'drill', 12,
          [doc('Labels and Selectors', K('concepts/overview/working-with-objects/labels/'))]],
        ['annotations-fields', 'annotation と field manager、誰が値を握っているか', 'concept', 10,
          [doc('Field Management', K('reference/using-api/server-side-apply/'))]],
        ['reconcile-loop', 'Pod を消しても復活するのはなぜか（reconcile を体感する）', 'challenge', 15,
          [doc('Controllers', K('concepts/architecture/controller/'))]],
      ]),
    chapter('k8s', 4, 'Workloads', 'ReplicaSet から CronJob まで、コントローラごとの前提の違い。',
      [doc('Workloads', K('concepts/workloads/'))], [
        ['replicaset', 'ReplicaSet が replicas を保つ仕組み', 'concept', 10,
          [doc('ReplicaSet', K('concepts/workloads/controllers/replicaset/'))]],
        ['deployment-strategy', 'RollingUpdate を maxSurge / maxUnavailable で制御する', 'drill', 15,
          [doc('Deployment', K('concepts/workloads/controllers/deployment/'))]],
        ['rollout-undo', 'rollout status / history / undo で安全に切り戻す', 'drill', 12,
          [doc('Deployment', K('concepts/workloads/controllers/deployment/'))]],
        ['statefulset', 'StatefulSet の順序保証と安定したネットワークID', 'concept', 15,
          [doc('StatefulSet', K('concepts/workloads/controllers/statefulset/'))]],
        ['daemonset', 'DaemonSet で全ノードに1つずつ配る', 'concept', 8,
          [doc('DaemonSet', K('concepts/workloads/controllers/daemonset/'))]],
        ['job-cronjob', 'Job の completions / parallelism と CronJob の重複実行', 'drill', 12,
          [doc('Job', K('concepts/workloads/controllers/job/'))]],
        ['boss-rollout-stuck', 'BOSS: ローリングアップデートが途中で止まった', 'boss', 20,
          [doc('Deployment', K('concepts/workloads/controllers/deployment/'))]],
      ]),
    chapter('k8s', 5, '設定と機密', 'イメージを焼き直さずに設定を差し替える。',
      [doc('ConfigMap', K('concepts/configuration/configmap/'))], [
        ['configmap', 'ConfigMap を env と volume で渡す違い', 'drill', 12],
        ['secret', 'Secret は暗号化ではない、という前提から始める', 'concept', 12,
          [doc('Secret', K('concepts/configuration/secret/'))]],
        ['immutable-reload', 'immutable ConfigMap と、設定変更を反映させる方法', 'concept', 10],
        ['boss-config-drift', 'BOSS: 設定を変えたのに古い値で動き続ける', 'boss', 18],
      ]),
    chapter('k8s', 6, 'ストレージ', 'Pod は消える。データは消えてはいけない。',
      [doc('Persistent Volumes', K('concepts/storage/persistent-volumes/'))], [
        ['volumes', 'emptyDir / hostPath / projected の使いどころ', 'concept', 10,
          [doc('Volumes', K('concepts/storage/volumes/'))]],
        ['pv-pvc', 'PV と PVC のバインド、アクセスモード', 'drill', 15],
        ['storageclass', 'StorageClass と動的プロビジョニング、reclaim policy', 'concept', 12,
          [doc('Storage Classes', K('concepts/storage/storage-classes/'))]],
        ['boss-pvc-pending', 'BOSS: PVC が Pending のまま Pod が起動しない', 'boss', 18],
      ]),
    chapter('k8s', 7, 'ネットワーク', 'Pod に届くまでの経路を、全部見える形で追う。',
      [doc('Service', K('concepts/services-networking/service/'))], [
        ['service-types', 'ClusterIP / NodePort / LoadBalancer / Headless', 'concept', 15],
        ['endpoints', 'Endpoints に載る条件は「selector 一致」かつ「Ready」', 'drill', 15],
        ['coredns', 'svc.ns.svc.cluster.local が解決される道筋', 'concept', 12,
          [doc('DNS for Services and Pods', K('concepts/services-networking/dns-pod-service/'))]],
        ['ingress', 'Ingress と IngressController、そして Gateway API', 'concept', 15,
          [doc('Ingress', K('concepts/services-networking/ingress/'))]],
        ['networkpolicy', 'NetworkPolicy はデフォルト許可を明示的に閉じる', 'drill', 15,
          [doc('Network Policies', K('concepts/services-networking/network-policies/'))]],
        ['boss-service-no-endpoint', 'BOSS: Pod は Running なのに Service で繋がらない', 'boss', 25],
      ]),
    chapter('k8s', 8, 'スケジューリング', 'どのノードに置くかは、要求と制約の交渉で決まる。',
      [doc('Assigning Pods to Nodes', K('concepts/scheduling-eviction/assign-pod-node/'))], [
        ['requests-limits', 'requests は配置の約束、limits は実行時の上限', 'concept', 15,
          [doc('Resource Management', K('concepts/configuration/manage-resources-containers/'))]],
        ['qos', 'QoS クラスと、退避されるのは誰か', 'concept', 10,
          [doc('Pod QoS', K('concepts/workloads/pods/pod-qos/'))]],
        ['taint-toleration', 'taint / toleration でノードを守る', 'drill', 15,
          [doc('Taints and Tolerations', K('concepts/scheduling-eviction/taint-and-toleration/'))]],
        ['affinity', 'nodeAffinity と podAntiAffinity', 'drill', 15],
        ['topology-spread', 'topologySpreadConstraints でゾーンに散らす', 'concept', 12,
          [doc('Topology Spread Constraints', K('concepts/scheduling-eviction/topology-spread-constraints/'))]],
        ['pdb-priority', 'PodDisruptionBudget と Priority / Preemption', 'concept', 15,
          [doc('Disruptions', K('concepts/workloads/pods/disruptions/'))]],
        ['boss-unschedulable', 'BOSS: 増やした Pod だけが Unschedulable', 'boss', 22],
      ]),
    chapter('k8s', 9, '可観測性とトラブルシュート', 'describe と events を読めるかどうかで速度が変わる。',
      [doc('Troubleshooting Applications', K('tasks/debug/debug-application/'))], [
        ['probes', 'liveness / readiness / startup の設計を間違えない', 'drill', 18,
          [doc('Configure Probes', K('tasks/configure-pod-container/configure-liveness-readiness-startup-probes/'))]],
        ['events-describe', 'describe の Events 欄を時系列で読む', 'drill', 12],
        ['logs-exec', 'logs --previous と exec で中を見る', 'drill', 12],
        ['failure-atlas', 'CrashLoopBackOff / ImagePullBackOff / OOMKilled / Pending の切り分け表', 'concept', 20],
        ['boss-crashloop', 'BOSS: 深夜に CrashLoopBackOff、原因を10分で特定せよ', 'boss', 25],
      ]),
    chapter('k8s', 10, 'セキュリティ', '最小権限を、動かしながら確かめる。',
      [doc('RBAC', K('reference/access-authn-authz/rbac/'))], [
        ['rbac', 'Role / RoleBinding と auth can-i', 'drill', 18],
        ['serviceaccount', 'ServiceAccount とトークンの扱い', 'concept', 12,
          [doc('Service Accounts', K('concepts/security/service-accounts/'))]],
        ['securitycontext', 'securityContext で権限を削る', 'drill', 15,
          [doc('Security Context', K('tasks/configure-pod-container/security-context/'))]],
        ['pod-security-admission', 'Pod Security Admission の3レベル', 'concept', 12,
          [doc('Pod Security Admission', K('concepts/security/pod-security-admission/'))]],
        ['boss-rbac-denied', 'BOSS: CI だけが Forbidden になる', 'boss', 20],
      ]),
    chapter('k8s', 11, 'スケールと無停止', '止めずに増やす、止めずに置き換える。',
      [doc('Horizontal Pod Autoscaling', K('tasks/run-application/horizontal-pod-autoscale/'))], [
        ['hpa', 'HPA のメトリクスと安定化ウィンドウ', 'drill', 15],
        ['autoscaling-layers', 'HPA / VPA / Cluster Autoscaler の役割の違い', 'concept', 12],
        ['graceful-shutdown', 'preStop と terminationGracePeriodSeconds', 'concept', 15,
          [doc('Container Lifecycle Hooks', K('concepts/containers/container-lifecycle-hooks/'))]],
        ['zero-downtime', 'readiness を使った無停止デプロイの組み立て', 'challenge', 20],
        ['boss-scale-drop', 'BOSS: スケールアウト中に 502 が出る', 'boss', 25],
      ]),
    chapter('k8s', 12, '運用', 'クラスタは動かし続けるもの。',
      [doc('Cluster Administration', K('concepts/cluster-administration/'))], [
        ['drain-cordon', 'drain / cordon でノードを安全に抜く', 'drill', 15,
          [doc('Safely Drain a Node', K('tasks/administer-cluster/safely-drain-node/'))]],
        ['upgrade', 'コントロールプレーンとノードの順序', 'concept', 15,
          [doc('Upgrading kubeadm clusters', K('tasks/administer-cluster/kubeadm/kubeadm-upgrade/'))]],
        ['etcd-backup', 'etcd のバックアップとリストア', 'concept', 15,
          [doc('Operating etcd', K('tasks/administer-cluster/configure-upgrade-etcd/'))]],
        ['helm-kustomize-gitops', 'Helm / Kustomize / GitOps の担当領域', 'concept', 15,
          [doc('Declarative Management with Kustomize', K('tasks/manage-kubernetes-objects/kustomization/'))]],
        ['boss-node-down', 'BOSS: ノードが1台落ちた。何が動き、何が止まったか', 'boss', 25],
      ]),
    chapter('k8s', 13, 'やってはいけない設定集', '事故の再現を通して、定石の理由を腹落ちさせる。',
      [doc('Configuration Best Practices', K('concepts/configuration/overview/'))], [
        ['latest-tag', 'latest タグが引き起こす「戻せない」事故', 'challenge', 15,
          [doc('Images', K('concepts/containers/images/'))]],
        ['no-limits', 'limits 未設定のノイジーネイバー再現', 'challenge', 15],
        ['hostpath-spof', 'hostPath とノード単一障害点', 'challenge', 15],
        ['quota-limitrange', 'ResourceQuota / LimitRange で事故を予防する', 'drill', 15,
          [doc('Resource Quotas', K('concepts/policy/resource-quotas/'))]],
        ['boss-postmortem', 'BOSS: 総合インシデント（原因3つを全て潰す）', 'boss', 35],
      ]),
  ],
};
